/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doan_nhom1;

import DAO.QLDiemSo;
import DAO.QLGiangVien;
import DAO.QLHocVien;
import DAO.QLLopHoc;
import DAO.QLLichHoc;
import Model.DiemSo;
import Model.GiangVien;
import Model.HocVien;
import Model.LopHoc;
import Model.LichHoc;
import java.awt.Color;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Administrator
 */
public class HomePage extends javax.swing.JFrame {

    DefaultTableModel tableHV;
    DefaultTableModel tableGV;
    DefaultTableModel tableKH;
    DefaultTableModel tableLH;
    DefaultTableModel tableDS;

    QLHocVien qlhv = new QLHocVien();
    QLGiangVien qlgv = new QLGiangVien();
    QLLopHoc qlkh = new QLLopHoc();
    QLLichHoc qllh = new QLLichHoc();
    QLDiemSo qlds = new QLDiemSo();

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        HienThiHocVien();
        HienThiGiangVien();
        HienThiKhoaHoc();
        HienThiLopHoc(1);
        HienThiDiemSo();
        jlbSLHV.setText(String.valueOf(qlhv.SoLuongHocVien()));
        jlpSLGV.setText(String.valueOf(qlgv.SLGiangVien()));
        jlbKhoaHoc.setText(String.valueOf(qlkh.SLKhoaHoc()));
        for (int i = 1; i <= 15; i++) {
            cbbTuan.addItem(i);
        }
        btnXoaKH.setEnabled(false);
        btnSuaKH.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel8 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnTrangChu = new javax.swing.JButton();
        btnHocVien = new javax.swing.JButton();
        btnGiaoVien = new javax.swing.JButton();
        btnKhoaHoc = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jpTrangchu = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jlbSLHV = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jlpSLGV = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jlbKhoaHoc = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jlbLopHoc = new javax.swing.JLabel();
        jpHocVien = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbHocVien = new javax.swing.JTable();
        jTextField4 = new javax.swing.JTextField();
        btnThemLH = new javax.swing.JButton();
        LOADLHBTN = new javax.swing.JButton();
        btnXOALH = new javax.swing.JButton();
        btnSUALH = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jpGiangVien = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbGiangVien = new javax.swing.JTable();
        jButton19 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        LOADBTN1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnSuaGV = new javax.swing.JButton();
        jpKhoaHoc = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbKhoaHoc = new javax.swing.JTable();
        jButton14 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        btnThemKH = new javax.swing.JButton();
        LOADKHBTN = new javax.swing.JButton();
        btnXoaKH = new javax.swing.JButton();
        btnSuaKH = new javax.swing.JButton();
        jpLopHoc = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbLopHoc = new javax.swing.JTable();
        jButton15 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        cbbTuan = new javax.swing.JComboBox<Integer>();
        jButton2 = new javax.swing.JButton();
        jpBaoCao = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tbDiemSo = new javax.swing.JTable();
        jTextField8 = new javax.swing.JTextField();
        btnThemDiem = new javax.swing.JButton();
        LOADBTNDiem = new javax.swing.JButton();
        btnXOADiem = new javax.swing.JButton();
        btnSUADiem = new javax.swing.JButton();
        jpCaiDat = new javax.swing.JPanel();
        btnDangXuat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnLopHoc = new javax.swing.JButton();
        btnBaoCao = new javax.swing.JButton();
        btnCaiDat = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(202, 250, 84));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-event-accepted-tentatively-30.png"))); // NOI18N
        jLabel20.setText("Số lượng khóa học");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel21.setText("100");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(40, 40, 40)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 34, 68));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 34, 68));

        jLabel1.setForeground(new java.awt.Color(0, 34, 68));

        btnTrangChu.setBackground(new java.awt.Color(255, 255, 255));
        btnTrangChu.setForeground(new java.awt.Color(0, 34, 68));
        btnTrangChu.setText("Trang Chủ");
        btnTrangChu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTrangChuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTrangChuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTrangChuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnTrangChuMouseReleased(evt);
            }
        });
        btnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChuActionPerformed(evt);
            }
        });

        btnHocVien.setBackground(new java.awt.Color(0, 34, 68));
        btnHocVien.setForeground(new java.awt.Color(255, 255, 255));
        btnHocVien.setText("Học Viên");
        btnHocVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHocVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHocVienMouseExited(evt);
            }
        });
        btnHocVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHocVienActionPerformed(evt);
            }
        });

        btnGiaoVien.setBackground(new java.awt.Color(0, 34, 68));
        btnGiaoVien.setForeground(new java.awt.Color(255, 255, 255));
        btnGiaoVien.setText("Giáo Viên");
        btnGiaoVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGiaoVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGiaoVienMouseExited(evt);
            }
        });
        btnGiaoVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiaoVienActionPerformed(evt);
            }
        });

        btnKhoaHoc.setBackground(new java.awt.Color(0, 34, 68));
        btnKhoaHoc.setForeground(new java.awt.Color(255, 255, 255));
        btnKhoaHoc.setText("Lớp Học");
        btnKhoaHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKhoaHocMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKhoaHocMouseExited(evt);
            }
        });
        btnKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoaHocActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.CardLayout());

        jpTrangchu.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(59, 250, 80));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-student-center-30.png"))); // NOI18N
        jLabel3.setText("Số lượng học viên");

        jlbSLHV.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbSLHV.setText("100");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jlbSLHV)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(50, 50, 50)
                .addComponent(jlbSLHV, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(61, 134, 250));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-tuition-30.png"))); // NOI18N
        jLabel6.setText("Số lượng giáo viên");

        jlpSLGV.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlpSLGV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlpSLGV.setText("100");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jlpSLGV)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(50, 50, 50)
                .addComponent(jlpSLGV, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(202, 250, 84));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-event-accepted-tentatively-30.png"))); // NOI18N
        jLabel18.setText("Số lượng khóa học");

        jlbKhoaHoc.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbKhoaHoc.setText("100");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jlbKhoaHoc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(50, 50, 50)
                .addComponent(jlbKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(162, 250, 246));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-classroom-30.png"))); // NOI18N
        jLabel22.setText("Số lượng lớp học");

        jlbLopHoc.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbLopHoc.setText("100");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jlbLopHoc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(50, 50, 50)
                .addComponent(jlbLopHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpTrangchuLayout = new javax.swing.GroupLayout(jpTrangchu);
        jpTrangchu.setLayout(jpTrangchuLayout);
        jpTrangchuLayout.setHorizontalGroup(
            jpTrangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTrangchuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpTrangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTrangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(622, Short.MAX_VALUE))
        );
        jpTrangchuLayout.setVerticalGroup(
            jpTrangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTrangchuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpTrangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpTrangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 157, Short.MAX_VALUE))
        );

        jPanel2.add(jpTrangchu, "card2");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("DANH SÁCH HỌC VIÊN");

        tbHocVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tbHocVien);

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });

        btnThemLH.setText("+Thêm học viên");
        btnThemLH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemLHActionPerformed(evt);
            }
        });

        LOADLHBTN.setText("Làm mới");
        LOADLHBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOADLHBTNActionPerformed(evt);
            }
        });

        btnXOALH.setText("Xóa");
        btnXOALH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXOALHActionPerformed(evt);
            }
        });

        btnSUALH.setText("Sửa");
        btnSUALH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSUALHActionPerformed(evt);
            }
        });

        jButton1.setText("Xem điểm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpHocVienLayout = new javax.swing.GroupLayout(jpHocVien);
        jpHocVien.setLayout(jpHocVienLayout);
        jpHocVienLayout.setHorizontalGroup(
            jpHocVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHocVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpHocVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jpHocVienLayout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSUALH, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXOALH, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LOADLHBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThemLH)))
                .addContainerGap())
        );
        jpHocVienLayout.setVerticalGroup(
            jpHocVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHocVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpHocVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4)
                    .addComponent(jLabel11)
                    .addComponent(btnThemLH)
                    .addComponent(LOADLHBTN)
                    .addComponent(btnXOALH)
                    .addComponent(btnSUALH)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jpHocVien, "card8");

        jpGiangVien.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("DANH SÁCH GIẢNG VIÊN");

        tbGiangVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tbGiangVien);

        jButton19.setText("Tìm kiếm");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton3.setText("+Thêm giảng viên");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        LOADBTN1.setText("Làm mới");
        LOADBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOADBTN1ActionPerformed(evt);
            }
        });

        jButton4.setText("Xóa");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnSuaGV.setText("Sửa");
        btnSuaGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaGVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpGiangVienLayout = new javax.swing.GroupLayout(jpGiangVien);
        jpGiangVien.setLayout(jpGiangVienLayout);
        jpGiangVienLayout.setHorizontalGroup(
            jpGiangVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGiangVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpGiangVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7)
                    .addGroup(jpGiangVienLayout.createSequentialGroup()
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 359, Short.MAX_VALUE)
                        .addComponent(btnSuaGV, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LOADBTN1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        jpGiangVienLayout.setVerticalGroup(
            jpGiangVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGiangVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpGiangVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5)
                    .addComponent(jButton19)
                    .addComponent(jLabel12)
                    .addComponent(jButton3)
                    .addComponent(LOADBTN1)
                    .addComponent(jButton4)
                    .addComponent(btnSuaGV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jpGiangVien, "card2");

        jpKhoaHoc.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("DANH SÁCH LỚP HỌC");

        tbKhoaHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbKhoaHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKhoaHocMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbKhoaHoc);

        jButton14.setText("Tìm kiếm");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        btnThemKH.setText("+Thêm lớp học");
        btnThemKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemKHActionPerformed(evt);
            }
        });

        LOADKHBTN.setText("Làm mới");
        LOADKHBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOADKHBTNActionPerformed(evt);
            }
        });

        btnXoaKH.setText("Xóa");
        btnXoaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaKHActionPerformed(evt);
            }
        });

        btnSuaKH.setText("Sửa");
        btnSuaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaKHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpKhoaHocLayout = new javax.swing.GroupLayout(jpKhoaHoc);
        jpKhoaHoc.setLayout(jpKhoaHocLayout);
        jpKhoaHocLayout.setHorizontalGroup(
            jpKhoaHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpKhoaHocLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpKhoaHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(jpKhoaHocLayout.createSequentialGroup()
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 373, Short.MAX_VALUE)
                        .addComponent(btnSuaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LOADKHBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThemKH)))
                .addContainerGap())
        );
        jpKhoaHocLayout.setVerticalGroup(
            jpKhoaHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpKhoaHocLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpKhoaHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6)
                    .addComponent(jButton14)
                    .addComponent(jLabel13)
                    .addComponent(btnThemKH)
                    .addComponent(LOADKHBTN)
                    .addComponent(btnXoaKH)
                    .addComponent(btnSuaKH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jpKhoaHoc, "card2");

        jpLopHoc.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("DANH SÁCH LỚP HỌC");

        tbLopHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tbLopHoc);

        jButton15.setText("Tìm kiếm");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton5.setText("+Thêm lớp học");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Xóa");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        cbbTuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTuanActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        javax.swing.GroupLayout jpLopHocLayout = new javax.swing.GroupLayout(jpLopHoc);
        jpLopHoc.setLayout(jpLopHocLayout);
        jpLopHocLayout.setHorizontalGroup(
            jpLopHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLopHocLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpLopHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(jpLopHocLayout.createSequentialGroup()
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 185, 185)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbTuan, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)))
                .addContainerGap())
        );
        jpLopHocLayout.setVerticalGroup(
            jpLopHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLopHocLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpLopHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7)
                    .addComponent(jButton15)
                    .addComponent(jLabel14)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(cbbTuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jpLopHoc, "card6");

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("DANH SÁCH ĐIỂM SỐ");

        tbDiemSo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(tbDiemSo);

        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField8KeyReleased(evt);
            }
        });

        btnThemDiem.setText("+Thêm điểm");
        btnThemDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDiemActionPerformed(evt);
            }
        });

        LOADBTNDiem.setText("Làm mới");
        LOADBTNDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOADBTNDiemActionPerformed(evt);
            }
        });

        btnXOADiem.setText("Xóa");
        btnXOADiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXOADiemActionPerformed(evt);
            }
        });

        btnSUADiem.setText("Sửa");
        btnSUADiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSUADiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBaoCaoLayout = new javax.swing.GroupLayout(jpBaoCao);
        jpBaoCao.setLayout(jpBaoCaoLayout);
        jpBaoCaoLayout.setHorizontalGroup(
            jpBaoCaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBaoCaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBaoCaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8)
                    .addGroup(jpBaoCaoLayout.createSequentialGroup()
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 353, Short.MAX_VALUE)
                        .addComponent(btnSUADiem, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXOADiem, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LOADBTNDiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThemDiem)))
                .addContainerGap())
        );
        jpBaoCaoLayout.setVerticalGroup(
            jpBaoCaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBaoCaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBaoCaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8)
                    .addComponent(jLabel15)
                    .addComponent(btnThemDiem)
                    .addComponent(LOADBTNDiem)
                    .addComponent(btnXOADiem)
                    .addComponent(btnSUADiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jpBaoCao, "card6");

        jpCaiDat.setBackground(new java.awt.Color(255, 255, 255));

        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCaiDatLayout = new javax.swing.GroupLayout(jpCaiDat);
        jpCaiDat.setLayout(jpCaiDatLayout);
        jpCaiDatLayout.setHorizontalGroup(
            jpCaiDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCaiDatLayout.createSequentialGroup()
                .addContainerGap(479, Short.MAX_VALUE)
                .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpCaiDatLayout.setVerticalGroup(
            jpCaiDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCaiDatLayout.createSequentialGroup()
                .addContainerGap(374, Short.MAX_VALUE)
                .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jpCaiDat, "card6");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Xin chào. Admin");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_mini.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        btnLopHoc.setBackground(new java.awt.Color(0, 34, 68));
        btnLopHoc.setForeground(new java.awt.Color(255, 255, 255));
        btnLopHoc.setText("Lịch Học");
        btnLopHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLopHocMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLopHocMouseExited(evt);
            }
        });
        btnLopHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLopHocActionPerformed(evt);
            }
        });

        btnBaoCao.setBackground(new java.awt.Color(0, 34, 68));
        btnBaoCao.setForeground(new java.awt.Color(255, 255, 255));
        btnBaoCao.setText("Điểm Số");
        btnBaoCao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBaoCaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBaoCaoMouseExited(evt);
            }
        });
        btnBaoCao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaoCaoActionPerformed(evt);
            }
        });

        btnCaiDat.setBackground(new java.awt.Color(0, 34, 68));
        btnCaiDat.setForeground(new java.awt.Color(255, 255, 255));
        btnCaiDat.setText("Cài Đặt");
        btnCaiDat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCaiDatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCaiDatMouseExited(evt);
            }
        });
        btnCaiDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaiDatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKhoaHoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHocVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGiaoVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnTrangChu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLopHoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBaoCao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCaiDat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel4))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHocVien, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGiaoVien, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(btnKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLopHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCaiDat, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoaHocActionPerformed
        // TODO add your handling code here:
        btnKhoaHoc.setBackground(Color.white);
        btnKhoaHoc.setForeground(new java.awt.Color(0, 34, 68));
        btnTrangChu.setBackground(new java.awt.Color(0, 34, 68));
        btnTrangChu.setForeground(Color.WHITE);
        btnHocVien.setBackground(new java.awt.Color(0, 34, 68));
        btnHocVien.setForeground(Color.WHITE);
        btnGiaoVien.setBackground(new java.awt.Color(0, 34, 68));
        btnGiaoVien.setForeground(Color.WHITE);
        btnLopHoc.setBackground(new java.awt.Color(0, 34, 68));
        btnLopHoc.setForeground(Color.WHITE);
        btnBaoCao.setBackground(new java.awt.Color(0, 34, 68));
        btnBaoCao.setForeground(Color.WHITE);
        btnCaiDat.setBackground(new java.awt.Color(0, 34, 68));
        btnCaiDat.setForeground(Color.WHITE);

        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();

        jPanel2.add(jpKhoaHoc);
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_btnKhoaHocActionPerformed

    private void btnGiaoVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiaoVienActionPerformed
        // TODO add your handling code here:
        btnGiaoVien.setBackground(Color.white);
        btnGiaoVien.setForeground(new java.awt.Color(0, 34, 68));
        btnTrangChu.setBackground(new java.awt.Color(0, 34, 68));
        btnTrangChu.setForeground(Color.WHITE);
        btnHocVien.setBackground(new java.awt.Color(0, 34, 68));
        btnHocVien.setForeground(Color.WHITE);
        btnKhoaHoc.setBackground(new java.awt.Color(0, 34, 68));
        btnKhoaHoc.setForeground(Color.WHITE);
        btnLopHoc.setBackground(new java.awt.Color(0, 34, 68));
        btnLopHoc.setForeground(Color.WHITE);
        btnBaoCao.setBackground(new java.awt.Color(0, 34, 68));
        btnBaoCao.setForeground(Color.WHITE);
        btnCaiDat.setBackground(new java.awt.Color(0, 34, 68));
        btnCaiDat.setForeground(Color.WHITE);

        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();

        jPanel2.add(jpGiangVien);
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_btnGiaoVienActionPerformed

    private void btnHocVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHocVienActionPerformed
        // TODO add your handling code here:
        btnHocVien.setBackground(Color.white);
        btnHocVien.setForeground(new java.awt.Color(0, 34, 68));
        btnTrangChu.setBackground(new java.awt.Color(0, 34, 68));
        btnTrangChu.setForeground(Color.WHITE);
        btnGiaoVien.setBackground(new java.awt.Color(0, 34, 68));
        btnGiaoVien.setForeground(Color.WHITE);
        btnKhoaHoc.setBackground(new java.awt.Color(0, 34, 68));
        btnKhoaHoc.setForeground(Color.WHITE);
        btnLopHoc.setBackground(new java.awt.Color(0, 34, 68));
        btnLopHoc.setForeground(Color.WHITE);
        btnBaoCao.setBackground(new java.awt.Color(0, 34, 68));
        btnBaoCao.setForeground(Color.WHITE);
        btnCaiDat.setBackground(new java.awt.Color(0, 34, 68));
        btnCaiDat.setForeground(Color.WHITE);

        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();

        jPanel2.add(jpHocVien);
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_btnHocVienActionPerformed

    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChuActionPerformed
        // TODO add your handling code here:
        btnTrangChu.setBackground(Color.white);
        btnTrangChu.setForeground(new java.awt.Color(0, 34, 68));
        btnHocVien.setBackground(new java.awt.Color(0, 34, 68));
        btnHocVien.setForeground(Color.WHITE);
        btnGiaoVien.setBackground(new java.awt.Color(0, 34, 68));
        btnGiaoVien.setForeground(Color.WHITE);
        btnKhoaHoc.setBackground(new java.awt.Color(0, 34, 68));
        btnKhoaHoc.setForeground(Color.WHITE);
        btnLopHoc.setBackground(new java.awt.Color(0, 34, 68));
        btnLopHoc.setForeground(Color.WHITE);
        btnBaoCao.setBackground(new java.awt.Color(0, 34, 68));
        btnBaoCao.setForeground(Color.WHITE);
        btnCaiDat.setBackground(new java.awt.Color(0, 34, 68));
        btnCaiDat.setForeground(Color.WHITE);

        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();

        jPanel2.add(jpTrangchu);
        jPanel2.repaint();
        jPanel2.revalidate();

        jlbSLHV.setText(String.valueOf(qlhv.SoLuongHocVien()));
        jlpSLGV.setText(String.valueOf(qlgv.SLGiangVien()));
        jlbKhoaHoc.setText(String.valueOf(qlkh.SLKhoaHoc()));

    }//GEN-LAST:event_btnTrangChuActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void btnLopHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLopHocActionPerformed
        // TODO add your handling code here:
        btnLopHoc.setBackground(Color.white);
        btnLopHoc.setForeground(new java.awt.Color(0, 34, 68));
        btnHocVien.setBackground(new java.awt.Color(0, 34, 68));
        btnHocVien.setForeground(Color.WHITE);
        btnGiaoVien.setBackground(new java.awt.Color(0, 34, 68));
        btnGiaoVien.setForeground(Color.WHITE);
        btnKhoaHoc.setBackground(new java.awt.Color(0, 34, 68));
        btnKhoaHoc.setForeground(Color.WHITE);
        btnTrangChu.setBackground(new java.awt.Color(0, 34, 68));
        btnTrangChu.setForeground(Color.WHITE);
        btnBaoCao.setBackground(new java.awt.Color(0, 34, 68));
        btnBaoCao.setForeground(Color.WHITE);
        btnCaiDat.setBackground(new java.awt.Color(0, 34, 68));
        btnCaiDat.setForeground(Color.WHITE);

        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();

        jPanel2.add(jpLopHoc);
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_btnLopHocActionPerformed

    private void btnBaoCaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaoCaoActionPerformed
        // TODO add your handling code here:
        btnBaoCao.setBackground(Color.white);
        btnBaoCao.setForeground(new java.awt.Color(0, 34, 68));
        btnHocVien.setBackground(new java.awt.Color(0, 34, 68));
        btnHocVien.setForeground(Color.WHITE);
        btnGiaoVien.setBackground(new java.awt.Color(0, 34, 68));
        btnGiaoVien.setForeground(Color.WHITE);
        btnKhoaHoc.setBackground(new java.awt.Color(0, 34, 68));
        btnKhoaHoc.setForeground(Color.WHITE);
        btnTrangChu.setBackground(new java.awt.Color(0, 34, 68));
        btnTrangChu.setForeground(Color.WHITE);
        btnLopHoc.setBackground(new java.awt.Color(0, 34, 68));
        btnLopHoc.setForeground(Color.WHITE);
        btnCaiDat.setBackground(new java.awt.Color(0, 34, 68));
        btnCaiDat.setForeground(Color.WHITE);

        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();

        jPanel2.add(jpBaoCao);
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_btnBaoCaoActionPerformed

    private void btnCaiDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaiDatActionPerformed
        // TODO add your handling code here:
        btnCaiDat.setBackground(Color.white);
        btnCaiDat.setForeground(new java.awt.Color(0, 34, 68));
        btnHocVien.setBackground(new java.awt.Color(0, 34, 68));
        btnHocVien.setForeground(Color.WHITE);
        btnGiaoVien.setBackground(new java.awt.Color(0, 34, 68));
        btnGiaoVien.setForeground(Color.WHITE);
        btnKhoaHoc.setBackground(new java.awt.Color(0, 34, 68));
        btnKhoaHoc.setForeground(Color.WHITE);
        btnTrangChu.setBackground(new java.awt.Color(0, 34, 68));
        btnTrangChu.setForeground(Color.WHITE);
        btnLopHoc.setBackground(new java.awt.Color(0, 34, 68));
        btnLopHoc.setForeground(Color.WHITE);
        btnBaoCao.setBackground(new java.awt.Color(0, 34, 68));
        btnBaoCao.setForeground(Color.WHITE);

        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();

        jPanel2.add(jpCaiDat);
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_btnCaiDatActionPerformed

    private void btnTrangChuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrangChuMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnTrangChuMousePressed

    private void btnTrangChuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrangChuMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_btnTrangChuMouseReleased

    private void btnTrangChuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrangChuMouseEntered

    }//GEN-LAST:event_btnTrangChuMouseEntered

    private void btnTrangChuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrangChuMouseExited

    }//GEN-LAST:event_btnTrangChuMouseExited

    private void btnHocVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHocVienMouseEntered

    }//GEN-LAST:event_btnHocVienMouseEntered

    private void btnHocVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHocVienMouseExited

    }//GEN-LAST:event_btnHocVienMouseExited

    private void btnGiaoVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGiaoVienMouseEntered

    }//GEN-LAST:event_btnGiaoVienMouseEntered

    private void btnGiaoVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGiaoVienMouseExited

    }//GEN-LAST:event_btnGiaoVienMouseExited

    private void btnKhoaHocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhoaHocMouseEntered

    }//GEN-LAST:event_btnKhoaHocMouseEntered

    private void btnKhoaHocMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhoaHocMouseExited

    }//GEN-LAST:event_btnKhoaHocMouseExited

    private void btnLopHocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLopHocMouseEntered

    }//GEN-LAST:event_btnLopHocMouseEntered

    private void btnLopHocMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLopHocMouseExited

    }//GEN-LAST:event_btnLopHocMouseExited

    private void btnBaoCaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBaoCaoMouseEntered

    }//GEN-LAST:event_btnBaoCaoMouseEntered

    private void btnBaoCaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBaoCaoMouseExited

    }//GEN-LAST:event_btnBaoCaoMouseExited

    private void btnCaiDatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCaiDatMouseEntered

    }//GEN-LAST:event_btnCaiDatMouseEntered

    private void btnCaiDatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCaiDatMouseExited

    }//GEN-LAST:event_btnCaiDatMouseExited

    private void btnThemLHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemLHActionPerformed
        // TODO add your handling code here:
        ThongTinHocVien tthv = new ThongTinHocVien();
       
        tthv.setVisible(true);
    }//GEN-LAST:event_btnThemLHActionPerformed

    private void LOADLHBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOADLHBTNActionPerformed
        // TODO add your handling code here:
        tableHV.setRowCount(0);
        ArrayList<HocVien> dataHV = qlhv.DocDL();
        for (HocVien hv : dataHV) {
            tableHV.addRow(new Object[]{hv.getMa_hv(), hv.getTen_hv(), hv.getNgay_sinh(), hv.getPhai(), hv.getDia_chi(), hv.getLien_he(), hv.getMa_khoa_hoc()});
        }
    }//GEN-LAST:event_LOADLHBTNActionPerformed

    private void btnXOALHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXOALHActionPerformed
        // TODO add your handling code here:
        int row = tbHocVien.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn học viên!");
        } else {
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa?!");

            if (confirm == JOptionPane.YES_OPTION) {
                String hvID = String.valueOf(tbHocVien.getValueAt(row, 0));
                if (qlhv.XoaDL(hvID) == 0) {
                    JOptionPane.showMessageDialog(this, "Xóa thất bại");
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                    HienThiHocVien();
                }
            }
        }
    }//GEN-LAST:event_btnXOALHActionPerformed

    private void btnSUALHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSUALHActionPerformed
        // TODO add your handling code here:
        int row = tbHocVien.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn học viên!");
        } else {
            String hvID = String.valueOf(tbHocVien.getValueAt(row, 0));
            try {
                new SuaHocVien(hvID).setVisible(true);
            } catch (ParseException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSUALHActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ThongTinGiangVien ttgv = new ThongTinGiangVien();
        ttgv.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void LOADBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOADBTN1ActionPerformed
        tableGV.setRowCount(0);
        ArrayList<GiangVien> dataGV = qlgv.DocDL();
        for (GiangVien hv : dataGV) {
            tableGV.addRow(new Object[]{hv.getMa_giang_vien(), hv.getTen_giang_vien(), hv.getPhai(), hv.getNgay_sinh(), hv.getDia_chi(), hv.getLien_he(), hv.getLuong_cb()});
        }
    }//GEN-LAST:event_LOADBTN1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int row = tbGiangVien.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn giảng viên!");
        } else {
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa?!");

            if (confirm == JOptionPane.YES_OPTION) {
                String hvID = String.valueOf(tbGiangVien.getValueAt(row, 0));
                if (qlgv.XoaDL(hvID) == 0) {
                    JOptionPane.showMessageDialog(this, "Xóa thất bại");
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                    HienThiGiangVien();
                }
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnSuaGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaGVActionPerformed
        // TODO add your handling code here:
        int row = tbGiangVien.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn giảng viên!");
        } else {
            String hvID = String.valueOf(tbGiangVien.getValueAt(row, 0));
            try {
                new SuaGiangVien(hvID).setVisible(true);
            } catch (ParseException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSuaGVActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void btnThemKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemKHActionPerformed
        // TODO add your handling code here:
        new ThongTinKhoaHoc().setVisible(true);
    }//GEN-LAST:event_btnThemKHActionPerformed

    private void LOADKHBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOADKHBTNActionPerformed
        // TODO add your handling code here:
        tableKH.setRowCount(0);
        ArrayList<LopHoc> dataGV = qlkh.DocDL();
        for (LopHoc hv : dataGV) {
            tableKH.addRow(new Object[]{hv.getMa_khoa_hoc(), hv.getTen_khoa_hoc(), hv.getMa_cap_do(), hv.getNgay_bat_dau(), hv.getNgay_ket_thuc(), qlkh.SiSoHocVien(hv.getMa_khoa_hoc())});
        }
    }//GEN-LAST:event_LOADKHBTNActionPerformed

    private void btnXoaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaKHActionPerformed
        // TODO add your handling code here:
        int row = tbKhoaHoc.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn khóa học!");
        } else {
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa?!");

            if (confirm == JOptionPane.YES_OPTION) {
                String hvID = String.valueOf(tbKhoaHoc.getValueAt(row, 0));
                if (qlkh.XoaDL(hvID) == 0) {
                    JOptionPane.showMessageDialog(this, "Xóa thất bại");
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                    HienThiKhoaHoc();
                }
            }
        }
    }//GEN-LAST:event_btnXoaKHActionPerformed

    private void btnSuaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaKHActionPerformed
        // TODO add your handling code here:
        int row = tbKhoaHoc.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn khóa học!");
        } else {
            String hvID = String.valueOf(tbKhoaHoc.getValueAt(row, 0));
            try {
                new SuaKhoaHoc(hvID).setVisible(true);
            } catch (ParseException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSuaKHActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new ThongTinLopHoc().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int tuan = (int) cbbTuan.getSelectedItem();
        int row = tbLopHoc.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn lớp học!");
        } else {
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa?!");

            if (confirm == JOptionPane.YES_OPTION) {
                String hvID = String.valueOf(tbLopHoc.getValueAt(row, 0));
                if (qllh.XoaDL(hvID) == 0) {
                    JOptionPane.showMessageDialog(this, "Xóa thất bại");
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                    HienThiLopHoc(tuan);
                }
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        new DangNhap().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        // TODO add your handling code here:
        String query = jTextField4.getText();
        filterHocVien(query);
    }//GEN-LAST:event_jTextField4KeyReleased

    private void cbbTuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTuanActionPerformed
        // TODO add your handling code here:
        int tuan = (int) cbbTuan.getSelectedItem();
        HienThiLopHoc(tuan);
    }//GEN-LAST:event_cbbTuanActionPerformed

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8KeyReleased

    private void btnThemDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDiemActionPerformed
        // TODO add your handling code here:
        new ThemDiemSo().setVisible(true);
    }//GEN-LAST:event_btnThemDiemActionPerformed

    private void LOADBTNDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOADBTNDiemActionPerformed
        // TODO add your handling code here:
        tableDS.setRowCount(0);
        ArrayList<DiemSo> dataGV = qlds.DocDL();
        for (DiemSo hv : dataGV) {
            tableDS.addRow(new Object[]{hv.getMa_hoc_vien(), hv.getDiem_so(), hv.getXep_loai(), hv.getNgay_thi()});
        }
    }//GEN-LAST:event_LOADBTNDiemActionPerformed

    private void btnXOADiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXOADiemActionPerformed
        // TODO add your handling code here:
         int row = tbDiemSo.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn học viên!");
        } else {
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa?!");

            if (confirm == JOptionPane.YES_OPTION) {
                String hvID = String.valueOf(tbDiemSo.getValueAt(row, 0));
                if (qlds.XoaDL(hvID) == 0) {
                    JOptionPane.showMessageDialog(this, "Xóa thất bại");
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                    HienThiDiemSo();
                }
            }
        }
    }//GEN-LAST:event_btnXOADiemActionPerformed

    private void btnSUADiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSUADiemActionPerformed
        // TODO add your handling code here:
        int row = tbDiemSo.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn học viên!");
        } else {
            String hvID = String.valueOf(tbDiemSo.getValueAt(row, 0));
            try {
                new SuaDiemSo(hvID).setVisible(true);
            } catch (ParseException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSUADiemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int row = tbHocVien.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn học viên!");
        } else {
            String hvID = String.valueOf(tbHocVien.getValueAt(row, 0));
            new ThongTinDiemSo(hvID).setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbKhoaHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKhoaHocMouseClicked
        // TODO add your handling code here:
        int row = tbKhoaHoc.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn lớp học!");
        }else{
            int si_so = (int) tbKhoaHoc.getValueAt(row, 5);
            if(si_so == 0){
                btnXoaKH.setEnabled(true);
                btnSuaKH.setEnabled(true);
            }else{
                btnXoaKH.setEnabled(false);
                btnSuaKH.setEnabled(false);
            }
        }
    }//GEN-LAST:event_tbKhoaHocMouseClicked
    private void HienThiHocVien() {
        tableHV = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tbHocVien.setModel(tableHV);
        tableHV.addColumn("Mã học viên");
        tableHV.addColumn("Tên học viên");
        tableHV.addColumn("Ngày sinh");
        tableHV.addColumn("Phái");
        tableHV.addColumn("Địa chỉ");
        tableHV.addColumn("Liên hệ");
        tableHV.addColumn("Mã khóa học");

        ArrayList<HocVien> dataHV = qlhv.DocDL();
        for (HocVien hv : dataHV) {
            tableHV.addRow(new Object[]{hv.getMa_hv(), hv.getTen_hv(), hv.getNgay_sinh(), hv.getPhai(), hv.getDia_chi(), hv.getLien_he(), hv.getMa_khoa_hoc()});
        }
    }

    private void HienThiGiangVien() {
        tableGV = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tbGiangVien.setModel(tableGV);
        tableGV.addColumn("Mã giảng viên");
        tableGV.addColumn("Tên giảng viên");
        tableGV.addColumn("Phái");
        tableGV.addColumn("Ngày sinh");
        tableGV.addColumn("Địa chỉ");
        tableGV.addColumn("Liên hệ");
        tableGV.addColumn("Lương");
        ArrayList<GiangVien> dataGV = qlgv.DocDL();
        for (GiangVien hv : dataGV) {
            tableGV.addRow(new Object[]{hv.getMa_giang_vien(), hv.getTen_giang_vien(), hv.getPhai(), hv.getNgay_sinh(), hv.getDia_chi(), hv.getLien_he(), hv.getLuong_cb()});
        }
    }

    private void HienThiKhoaHoc() {
        tableKH = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tbKhoaHoc.setModel(tableKH);
        tableKH.addColumn("Mã khóa học");
        tableKH.addColumn("Tên khóa học");
        tableKH.addColumn("Cấp độ");
        tableKH.addColumn("Ngày bắt đầu");
        tableKH.addColumn("Ngày kết thúc");
        tableKH.addColumn("Sỉ số");
        ArrayList<LopHoc> dataGV = qlkh.DocDL();
        for (LopHoc hv : dataGV) {
            tableKH.addRow(new Object[]{hv.getMa_khoa_hoc(), hv.getTen_khoa_hoc(), hv.getMa_cap_do(), hv.getNgay_bat_dau(), hv.getNgay_ket_thuc(), qlkh.SiSoHocVien(hv.getMa_khoa_hoc())});
        }
    }

    private void HienThiLopHoc(int tuan) {
        tableLH = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tbLopHoc.setModel(tableLH);
        tableLH.addColumn("Mã lớp");
        tableLH.addColumn("Mã giáo viên");
        tableLH.addColumn("Lịch học");
        tableLH.addColumn("Phòng học");
        tableLH.addColumn("Tuần");
        tableLH.setRowCount(0);
        ArrayList<LichHoc> dataGV = qllh.DocDL(tuan);
        for (LichHoc hv : dataGV) {
            tableLH.addRow(new Object[]{hv.getMa_lop_hoc(), hv.getMa_giang_vien(), hv.getLich_hoc(), hv.getPhong_hoc(), hv.getTuan()});
        }
    }

    private void HienThiDiemSo() {
        tableDS = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tbDiemSo.setModel(tableDS);
        tableDS.addColumn("Mã học viên");
        tableDS.addColumn("Điểm");
        tableDS.addColumn("Xếp loại");
        tableDS.addColumn("Ngày thi");;
        ArrayList<DiemSo> dataGV = qlds.DocDL();
        for (DiemSo hv : dataGV) {
            tableDS.addRow(new Object[]{hv.getMa_hoc_vien(), hv.getDiem_so(), hv.getXep_loai(), hv.getNgay_thi()});
        }
    }

    private void filterHocVien(String query) {
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(tableHV);
        tbHocVien.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(query));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LOADBTN1;
    private javax.swing.JButton LOADBTNDiem;
    private javax.swing.JButton LOADKHBTN;
    private javax.swing.JButton LOADLHBTN;
    private javax.swing.JButton btnBaoCao;
    private javax.swing.JButton btnCaiDat;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnGiaoVien;
    private javax.swing.JButton btnHocVien;
    private javax.swing.JButton btnKhoaHoc;
    private javax.swing.JButton btnLopHoc;
    private javax.swing.JButton btnSUADiem;
    private javax.swing.JButton btnSUALH;
    private javax.swing.JButton btnSuaGV;
    private javax.swing.JButton btnSuaKH;
    private javax.swing.JButton btnThemDiem;
    private javax.swing.JButton btnThemKH;
    private javax.swing.JButton btnThemLH;
    private javax.swing.JButton btnTrangChu;
    private javax.swing.JButton btnXOADiem;
    private javax.swing.JButton btnXOALH;
    private javax.swing.JButton btnXoaKH;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<Integer> cbbTuan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel jlbKhoaHoc;
    private javax.swing.JLabel jlbLopHoc;
    private javax.swing.JLabel jlbSLHV;
    private javax.swing.JLabel jlpSLGV;
    private javax.swing.JPanel jpBaoCao;
    private javax.swing.JPanel jpCaiDat;
    private javax.swing.JPanel jpGiangVien;
    private javax.swing.JPanel jpHocVien;
    private javax.swing.JPanel jpKhoaHoc;
    private javax.swing.JPanel jpLopHoc;
    private javax.swing.JPanel jpTrangchu;
    private javax.swing.JTable tbDiemSo;
    private javax.swing.JTable tbGiangVien;
    private javax.swing.JTable tbHocVien;
    private javax.swing.JTable tbKhoaHoc;
    private javax.swing.JTable tbLopHoc;
    // End of variables declaration//GEN-END:variables
}
